### PR TITLE
Tmpdir cleanup fixes

### LINKED ISSUE #380: bundler_path is not cleaned
After running the buildpack I see several dirs under `/tmp` of the following form `d20150505-26344-10tqj82`. This appears to match the names selected by `Dir#mktmpdir`, which is called [here](https://github.com/heroku/heroku-buildpack-ruby/blob/881d794a8f33d102561798f696c049f5178ce60d/lib/language_pack/helpers/bundler_wrapper.rb#L22). 

```console
# ruby -rtmpdir -e 'puts Dir.mktmpdir'
/tmp/d20150506-31344-h7lhxa
```

I couldn't find any place where `LanguagePack::Helpers::BundlerWrapper#clean` is called, and the fact that files are still in place after compiling the buildpack, makes me think it is not being called.

Leaving these files in place over time gets to be rather unweildy since each run of the buildpack includes several (7) copies of bundler.

```console
# ls -l /tmp/
total 44
drwx------ 2 api  api  4096 May  6 19:32 bundler20150506-2395-vviidb/
drwx------ 2 api  api  4096 May  6 19:32 bundler20150506-2403-1d74l0m/
drwx------ 3 api  api  4096 May  6 19:32 d20150506-1966-14upe2h/
drwx------ 3 api  api  4096 May  6 19:32 d20150506-1966-16qwfwb/
drwx------ 3 api  api  4096 May  6 19:32 d20150506-1966-1d6ew6q/
drwx------ 3 api  api  4096 May  6 19:32 d20150506-1966-1d95231/
drwx------ 3 api  api  4096 May  6 19:32 d20150506-1966-1hmn5pc/
drwx------ 3 api  api  4096 May  6 19:32 d20150506-1966-5b58c6/

# tree /tmp/d20150506-1966-14upe2h/
/tmp/d20150506-1966-14upe2h/
└── bundler-1.7.12
    ├── bin
    │   ├── bundle
    │   └── bundler
    ├── cache
    ├── doc
    ├── gems
    │   └── bundler-1.7.12
    │       ├── bin
    │       │   ├── bundle
    │       │   ├── bundler
    │       │   └── bundle_ruby
    │       ├── bundler.gemspec
    │       ├── CHANGELOG.md
    │       ├── CONTRIBUTING.md
    │       ├── DEVELOPMENT.md
    │       ├── ISSUES.md
    │       ├── lib
    │       │   ├── bundler
    │       │   │   ├── anonymizable_uri.rb
    │       │   │   ├── capistrano.rb
    │       │   │   ├── cli
    │       │   │   │   ├── binstubs.rb
    │       │   │   │   ├── cache.rb
    │       │   │   │   ├── check.rb
    │       │   │   │   ├── clean.rb
    │       │   │   │   ├── common.rb
    │       │   │   │   ├── config.rb
    │       │   │   │   ├── console.rb
    │       │   │   │   ├── exec.rb
    │       │   │   │   ├── gem.rb
    │       │   │   │   ├── init.rb
    │       │   │   │   ├── inject.rb
    │       │   │   │   ├── install.rb
    │       │   │   │   ├── open.rb
    │       │   │   │   ├── outdated.rb
    │       │   │   │   ├── package.rb
    │       │   │   │   ├── platform.rb
    │       │   │   │   ├── show.rb
    │       │   │   │   ├── update.rb
    │       │   │   │   └── viz.rb
    │       │   │   ├── cli.rb
    │       │   │   ├── constants.rb
    │       │   │   ├── current_ruby.rb
    │       │   │   ├── definition.rb
    │       │   │   ├── dependency.rb
    │       │   │   ├── deployment.rb
    │       │   │   ├── dep_proxy.rb
    │       │   │   ├── deprecate.rb
    │       │   │   ├── dsl.rb
    │       │   │   ├── endpoint_specification.rb
    │       │   │   ├── environment.rb
    │       │   │   ├── env.rb
    │       │   │   ├── fetcher.rb
    │       │   │   ├── friendly_errors.rb
    │       │   │   ├── gem_helper.rb
    │       │   │   ├── gem_helpers.rb
    │       │   │   ├── gem_installer.rb
    │       │   │   ├── gem_path_manipulation.rb
    │       │   │   ├── gem_tasks.rb
    │       │   │   ├── graph.rb
    │       │   │   ├── index.rb
    │       │   │   ├── injector.rb
    │       │   │   ├── installer.rb
    │       │   │   ├── lazy_specification.rb
    │       │   │   ├── lockfile_parser.rb
    │       │   │   ├── man
    │       │   │   │   ├── bundle
    │       │   │   │   ├── bundle-config
    │       │   │   │   ├── bundle-config.txt
    │       │   │   │   ├── bundle-exec
    │       │   │   │   ├── bundle-exec.txt
    │       │   │   │   ├── bundle-install
    │       │   │   │   ├── bundle-install.txt
    │       │   │   │   ├── bundle-package
    │       │   │   │   ├── bundle-package.txt
    │       │   │   │   ├── bundle-platform
    │       │   │   │   ├── bundle-platform.txt
    │       │   │   │   ├── bundle.txt
    │       │   │   │   ├── bundle-update
    │       │   │   │   ├── bundle-update.txt
    │       │   │   │   ├── gemfile.5
    │       │   │   │   └── gemfile.5.txt
    │       │   │   ├── match_platform.rb
    │       │   │   ├── parallel_workers
    │       │   │   │   ├── thread_worker.rb
    │       │   │   │   ├── unix_worker.rb
    │       │   │   │   └── worker.rb
    │       │   │   ├── parallel_workers.rb
    │       │   │   ├── psyched_yaml.rb
    │       │   │   ├── remote_specification.rb
    │       │   │   ├── resolver.rb
    │       │   │   ├── retry.rb
    │       │   │   ├── ruby_dsl.rb
    │       │   │   ├── rubygems_ext.rb
    │       │   │   ├── rubygems_integration.rb
    │       │   │   ├── ruby_version.rb
    │       │   │   ├── runtime.rb
    │       │   │   ├── settings.rb
    │       │   │   ├── setup.rb
    │       │   │   ├── shared_helpers.rb
    │       │   │   ├── similarity_detector.rb
    │       │   │   ├── source
    │       │   │   │   ├── git
    │       │   │   │   │   └── git_proxy.rb
    │       │   │   │   ├── git.rb
    │       │   │   │   ├── path
    │       │   │   │   │   └── installer.rb
    │       │   │   │   ├── path.rb
    │       │   │   │   └── rubygems.rb
    │       │   │   ├── source_list.rb
    │       │   │   ├── source.rb
    │       │   │   ├── spec_set.rb
    │       │   │   ├── ssl_certs
    │       │   │   │   ├── AddTrustExternalCARoot-2048.pem
    │       │   │   │   ├── AddTrustExternalCARoot.pem
    │       │   │   │   ├── certificate_manager.rb
    │       │   │   │   ├── Class3PublicPrimaryCertificationAuthority.pem
    │       │   │   │   ├── DigiCertHighAssuranceEVRootCA.pem
    │       │   │   │   ├── EntrustnetSecureServerCertificationAuthority.pem
    │       │   │   │   └── GeoTrustGlobalCA.pem
    │       │   │   ├── templates
    │       │   │   │   ├── Executable
    │       │   │   │   ├── Executable.standalone
    │       │   │   │   ├── Gemfile
    │       │   │   │   └── newgem
    │       │   │   │       ├── bin
    │       │   │   │       │   └── newgem.tt
    │       │   │   │       ├── ext
    │       │   │   │       │   └── newgem
    │       │   │   │       │       ├── extconf.rb.tt
    │       │   │   │       │       ├── newgem.c.tt
    │       │   │   │       │       └── newgem.h.tt
    │       │   │   │       ├── Gemfile.tt
    │       │   │   │       ├── gitignore.tt
    │       │   │   │       ├── lib
    │       │   │   │       │   ├── newgem
    │       │   │   │       │   │   └── version.rb.tt
    │       │   │   │       │   └── newgem.rb.tt
    │       │   │   │       ├── LICENSE.txt.tt
    │       │   │   │       ├── newgem.gemspec.tt
    │       │   │   │       ├── Rakefile.tt
    │       │   │   │       ├── README.md.tt
    │       │   │   │       ├── rspec.tt
    │       │   │   │       ├── spec
    │       │   │   │       │   ├── newgem_spec.rb.tt
    │       │   │   │       │   └── spec_helper.rb.tt
    │       │   │   │       └── test
    │       │   │   │           ├── minitest_helper.rb.tt
    │       │   │   │           └── test_newgem.rb.tt
    │       │   │   ├── ui
    │       │   │   │   ├── rg_proxy.rb
    │       │   │   │   ├── shell.rb
    │       │   │   │   └── silent.rb
    │       │   │   ├── ui.rb
    │       │   │   ├── vendor
    │       │   │   │   ├── net
    │       │   │   │   │   └── http
    │       │   │   │   │       ├── faster.rb
    │       │   │   │   │       ├── persistent
    │       │   │   │   │       │   └── ssl_reuse.rb
    │       │   │   │   │       └── persistent.rb
    │       │   │   │   ├── thor
    │       │   │   │   │   ├── actions
    │       │   │   │   │   │   ├── create_file.rb
    │       │   │   │   │   │   ├── create_link.rb
    │       │   │   │   │   │   ├── directory.rb
    │       │   │   │   │   │   ├── empty_directory.rb
    │       │   │   │   │   │   ├── file_manipulation.rb
    │       │   │   │   │   │   └── inject_into_file.rb
    │       │   │   │   │   ├── actions.rb
    │       │   │   │   │   ├── base.rb
    │       │   │   │   │   ├── command.rb
    │       │   │   │   │   ├── core_ext
    │       │   │   │   │   │   ├── hash_with_indifferent_access.rb
    │       │   │   │   │   │   ├── io_binary_read.rb
    │       │   │   │   │   │   └── ordered_hash.rb
    │       │   │   │   │   ├── error.rb
    │       │   │   │   │   ├── group.rb
    │       │   │   │   │   ├── invocation.rb
    │       │   │   │   │   ├── line_editor
    │       │   │   │   │   │   ├── basic.rb
    │       │   │   │   │   │   └── readline.rb
    │       │   │   │   │   ├── line_editor.rb
    │       │   │   │   │   ├── parser
    │       │   │   │   │   │   ├── argument.rb
    │       │   │   │   │   │   ├── arguments.rb
    │       │   │   │   │   │   ├── option.rb
    │       │   │   │   │   │   └── options.rb
    │       │   │   │   │   ├── parser.rb
    │       │   │   │   │   ├── rake_compat.rb
    │       │   │   │   │   ├── runner.rb
    │       │   │   │   │   ├── shell
    │       │   │   │   │   │   ├── basic.rb
    │       │   │   │   │   │   ├── color.rb
    │       │   │   │   │   │   └── html.rb
    │       │   │   │   │   ├── shell.rb
    │       │   │   │   │   ├── util.rb
    │       │   │   │   │   └── version.rb
    │       │   │   │   └── thor.rb
    │       │   │   ├── vendored_persistent.rb
    │       │   │   ├── vendored_thor.rb
    │       │   │   ├── version.rb
    │       │   │   └── vlad.rb
    │       │   └── bundler.rb
    │       ├── LICENSE.md
    │       ├── man
    │       │   ├── bundle-config.ronn
    │       │   ├── bundle-exec.ronn
    │       │   ├── bundle-install.ronn
    │       │   ├── bundle-package.ronn
    │       │   ├── bundle-platform.ronn
    │       │   ├── bundle.ronn
    │       │   ├── bundle-update.ronn
    │       │   ├── gemfile.5.ronn
    │       │   └── index.txt
    │       ├── Rakefile
    │       ├── README.md
    │       ├── spec
    │       │   ├── bundler
    │       │   │   ├── anonymizable_uri_spec.rb
    │       │   │   ├── bundler_spec.rb
    │       │   │   ├── cli_spec.rb
    │       │   │   ├── definition_spec.rb
    │       │   │   ├── dsl_spec.rb
    │       │   │   ├── friendly_errors_spec.rb
    │       │   │   ├── gem_helper_spec.rb
    │       │   │   ├── psyched_yaml_spec.rb
    │       │   │   ├── retry_spec.rb
    │       │   │   ├── settings_spec.rb
    │       │   │   ├── source
    │       │   │   │   └── rubygems_spec.rb
    │       │   │   └── source_list_spec.rb
    │       │   ├── cache
    │       │   │   ├── gems_spec.rb
    │       │   │   ├── git_spec.rb
    │       │   │   ├── path_spec.rb
    │       │   │   └── platform_spec.rb
    │       │   ├── commands
    │       │   │   ├── binstubs_spec.rb
    │       │   │   ├── check_spec.rb
    │       │   │   ├── clean_spec.rb
    │       │   │   ├── config_spec.rb
    │       │   │   ├── console_spec.rb
    │       │   │   ├── exec_spec.rb
    │       │   │   ├── help_spec.rb
    │       │   │   ├── init_spec.rb
    │       │   │   ├── inject_spec.rb
    │       │   │   ├── licenses_spec.rb
    │       │   │   ├── newgem_spec.rb
    │       │   │   ├── open_spec.rb
    │       │   │   ├── outdated_spec.rb
    │       │   │   ├── package_spec.rb
    │       │   │   └── show_spec.rb
    │       │   ├── install
    │       │   │   ├── binstubs_spec.rb
    │       │   │   ├── bundler_spec.rb
    │       │   │   ├── deploy_spec.rb
    │       │   │   ├── gemfile
    │       │   │   │   ├── gemspec_spec.rb
    │       │   │   │   ├── git_spec.rb
    │       │   │   │   └── path_spec.rb
    │       │   │   ├── gemfile_spec.rb
    │       │   │   ├── gems
    │       │   │   │   ├── c_ext_spec.rb
    │       │   │   │   ├── dependency_api_spec.rb
    │       │   │   │   ├── env_spec.rb
    │       │   │   │   ├── flex_spec.rb
    │       │   │   │   ├── groups_spec.rb
    │       │   │   │   ├── mirror_spec.rb
    │       │   │   │   ├── platform_spec.rb
    │       │   │   │   ├── post_install_spec.rb
    │       │   │   │   ├── resolving_spec.rb
    │       │   │   │   ├── simple_case_spec.rb
    │       │   │   │   ├── sources_spec.rb
    │       │   │   │   ├── standalone_spec.rb
    │       │   │   │   ├── sudo_spec.rb
    │       │   │   │   └── win32_spec.rb
    │       │   │   ├── gemspecs_spec.rb
    │       │   │   ├── path_spec.rb
    │       │   │   ├── post_bundle_message_spec.rb
    │       │   │   ├── prereleases_spec.rb
    │       │   │   ├── security_policy_spec.rb
    │       │   │   └── upgrade_spec.rb
    │       │   ├── lock
    │       │   │   ├── git_spec.rb
    │       │   │   └── lockfile_spec.rb
    │       │   ├── other
    │       │   │   ├── bundle_ruby_spec.rb
    │       │   │   ├── cli_dispatch_spec.rb
    │       │   │   ├── ext_spec.rb
    │       │   │   ├── platform_spec.rb
    │       │   │   └── ssl_cert_spec.rb
    │       │   ├── quality_spec.rb
    │       │   ├── realworld
    │       │   │   ├── dependency_api_spec.rb
    │       │   │   ├── edgecases_spec.rb
    │       │   │   └── parallel_spec.rb
    │       │   ├── resolver
    │       │   │   ├── basic_spec.rb
    │       │   │   └── platform_spec.rb
    │       │   ├── runtime
    │       │   │   ├── executable_spec.rb
    │       │   │   ├── load_spec.rb
    │       │   │   ├── platform_spec.rb
    │       │   │   ├── require_spec.rb
    │       │   │   ├── setup_spec.rb
    │       │   │   └── with_clean_env_spec.rb
    │       │   ├── spec_helper.rb
    │       │   ├── support
    │       │   │   ├── artifice
    │       │   │   │   ├── endopint_marshal_fail_basic_authentication.rb
    │       │   │   │   ├── endpoint_500.rb
    │       │   │   │   ├── endpoint_api_forbidden.rb
    │       │   │   │   ├── endpoint_api_missing.rb
    │       │   │   │   ├── endpoint_basic_authentication.rb
    │       │   │   │   ├── endpoint_creds_diff_host.rb
    │       │   │   │   ├── endpoint_extra_missing.rb
    │       │   │   │   ├── endpoint_extra.rb
    │       │   │   │   ├── endpoint_fallback.rb
    │       │   │   │   ├── endpoint_host_redirect.rb
    │       │   │   │   ├── endpoint_marshal_fail.rb
    │       │   │   │   ├── endpoint.rb
    │       │   │   │   ├── endpoint_redirect.rb
    │       │   │   │   ├── endpoint_strict_basic_authentication.rb
    │       │   │   │   └── endpoint_timeout.rb
    │       │   │   ├── builders.rb
    │       │   │   ├── fakeweb
    │       │   │   │   ├── rack-1.0.0.marshal
    │       │   │   │   └── windows.rb
    │       │   │   ├── hax.rb
    │       │   │   ├── helpers.rb
    │       │   │   ├── indexes.rb
    │       │   │   ├── matchers.rb
    │       │   │   ├── path.rb
    │       │   │   ├── permissions.rb
    │       │   │   ├── platforms.rb
    │       │   │   ├── ruby_ext.rb
    │       │   │   ├── rubygems_ext.rb
    │       │   │   ├── streams.rb
    │       │   │   └── sudo.rb
    │       │   └── update
    │       │       ├── gems_spec.rb
    │       │       ├── git_spec.rb
    │       │       └── path_spec.rb
    │       └── UPGRADING.md
    └── specifications
        └── bundler-1.7.12.gemspec

55 directories, 293 files
```

### PR DESCRIPTION
**Pull request by mikehale**
Fixes #380

I'm not certain about including the "hack to cleanup after bundler" commit, but the first 2 should be good to go.

/cc @schneems

### CODE REVIEW

**Comment by mikehale** [comment]
@schneems bump

File: lib/language_pack/ruby.rb [hunk 1]
```diff
@@ -29,7 +29,7 @@ def self.use?
   end
 
   def self.bundler
-    @bundler ||= LanguagePack::Helpers::BundlerWrapper.new.install
+    @@bundler ||= LanguagePack::Helpers::BundlerWrapper.new.install
```
Comment (schneems) [inline lib/language_pack/ruby.rb]: We're essentially doing this allready, but without using the extremely confusing class instance variables:

```ruby
  def self.bundler
    @bundler ||= LanguagePack::Helpers::BundlerWrapper.new.install
  end

  def bundler
    self.class.bundler
  end
```

Is there another reason we need this?

File: lib/language_pack/helpers/bundler_wrapper.rb [hunk 2]
```diff
@@ -37,7 +38,16 @@ def install
...
-    FileUtils.remove_entry_secure(bundler_path) if Dir.exist?(bundler_path)
+    FileUtils.remove_entry_secure(@bundler_tmp) if Dir.exist?(@bundler_tmp)
+
+    if LanguagePack::Ruby::BUNDLER_VERSION  == "1.7.12"
+      # Hack to cleanup after pre 1.8 versions of bundler. See https://github.com/bundler/bundler/pull/3277/
+      Dir["#{Dir.tmpdir}/bundler*"].each do |dir|
+        FileUtils.remove_entry_secure(dir) if Dir.exist?(dir) && File.stat(dir).writable?
+      end
+    else
+      raise "Bundler cleanup hack is out of date, please update it to be compatible with #{LanguagePack::Ruby::BUNDLER_VERSION}"
```
Comment (schneems) [inline lib/language_pack/helpers/bundler_wrapper.rb]: We're about to test run 1.9.6. We will have to take this raise out. How critical is this behavior for you? Should we remove the raise or can I remove it all? Was going to merge 1.9.6 into master sometime this week, shoot to deploy thursday if no issues.

**Comment by schneems** [comment]
The fundamentals look good. In the future if you make pull requests from the heroku/ org on the buildpack instead of your org then tests will run with the right credentials. I'm going to pull down your changes, remove the raise, the class instance variable and run tests in another PR. If that's all green we can merge today.

**Comment by schneems** [comment]
Nevermind, just saw that you did make the PR from the right org, thanks! The second travis test always fails since it's on the wrong branch. 

So this looks good, can you remove the raise and the class instance variable, or you want me to do it?

File: lib/language_pack/ruby.rb (hunk 1 above)
Comment (mikehale) [inline lib/language_pack/ruby.rb]: Yeah, I don't exactly understand why, but I think it is not working as intended with just `@bundler`. I put a print statement in the BundleWrapper initialize method and ran the buildpack and saw it be initialized multiple times (once for each ruby subclass I think). Changing to `@@bundler` caused BundlerWrapper to only be initialized once.

File: lib/language_pack/helpers/bundler_wrapper.rb (hunk 2 above)
Comment (mikehale) [inline lib/language_pack/helpers/bundler_wrapper.rb]: Ah if 1.9.6 is going out this week that is probably soon enough to not worry about this hack. Assuming we can get a new version of the buildpack within a week or two I'm ok just removing this whole if block since the desired behavior should be included in the new version of bundler.

File: lib/language_pack/ruby.rb (hunk 1 above)
Comment (schneems) [inline lib/language_pack/ruby.rb]: Think i figured out what's going on. You're right. We detect which pack to use

https://github.com/heroku/heroku-buildpack-ruby/blob/e99ccea2cf3343f4d8ef7ffc813f754c3d5c090d/bin/compile#L12-L16

To do that we loop through all the packs and call detect.

https://github.com/heroku/heroku-buildpack-ruby/blob/e99ccea2cf3343f4d8ef7ffc813f754c3d5c090d/lib/language_pack.rb#L16-L20

To do that for Rails we have to use the bundler lockfile parser from bundler https://github.com/heroku/heroku-buildpack-ruby/blob/e99ccea2cf3343f4d8ef7ffc813f754c3d5c090d/lib/language_pack/rails4.rb#L12-L16

Since the `self.class` is different for each subclass instance it would instantiate and create a new bundler wrapper instance for each detect. Good catch, let's leave that in there. Thanks!
